version: '3'

services:
  directus:
    build: .
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - .env
    restart: unless-stopped 